//! Restricted Foundation typedstream grammar, independently generated by
//! tools/generate-decoder-fixtures.m. Unknown classes/types preserve the legacy
//! text + attachment fallback. Nothing is instantiated or searched heuristically.
const std = @import("std");
const u = @import("../../common.zig");
const t = @import("../../protocol/types.zig");
const Failure = error{ Malformed, Unsupported, Oversized, OutOfMemory };
const Entry = struct { key: []const u8, value: Object };
const Object = union(enum) { pending, class: []const u8, text: []const u8, number: i64, dict: []Entry, attributed: Body };
const Range = struct { length: usize, attributes: []Entry };
const Body = struct { text: []const u8, ranges: []Range };
const Reader = struct {
    a: u.Allocator,
    bytes: []const u8,
    pos: usize = 0,
    strings: std.ArrayList([]const u8) = .empty,
    objects: std.ArrayList(Object) = .empty,
    visits: usize = 0,
    fn take(self: *Reader, length: usize) Failure![]const u8 {
        if (length > self.bytes.len - self.pos) return error.Malformed;
        const result = self.bytes[self.pos..][0..length];
        self.pos += length;
        return result;
    }
    fn byte(self: *Reader) Failure!u8 {
        return (try self.take(1))[0];
    }
    fn integer(self: *Reader, signed: bool) Failure!i64 {
        const lead = try self.byte();
        return switch (lead) {
            0x81 => if (signed) std.mem.readInt(i16, (try self.take(2))[0..2], .little) else std.mem.readInt(u16, (try self.take(2))[0..2], .little),
            0x82 => if (signed) std.mem.readInt(i32, (try self.take(4))[0..4], .little) else std.mem.readInt(u32, (try self.take(4))[0..4], .little),
            0x80, 0x83...0x86 => error.Unsupported,
            else => if (signed) @as(i8, @bitCast(lead)) else lead,
        };
    }
    fn readLength(self: *Reader) Failure!usize {
        const n = try self.integer(false);
        if (n < 0 or n > t.max_decode) return error.Oversized;
        return @intCast(n);
    }
    fn ref(self: *Reader, count: usize) Failure!usize {
        const n = try self.integer(true);
        if (n < -110 or n + 110 >= count) return error.Malformed;
        return @intCast(n + 110);
    }
    fn shared(self: *Reader) Failure![]const u8 {
        if (self.pos >= self.bytes.len) return error.Malformed;
        if (self.bytes[self.pos] != 0x84) return self.strings.items[try self.ref(self.strings.items.len)];
        self.pos += 1;
        const text = try self.take(try self.readLength());
        if (self.strings.items.len >= 8192) return error.Oversized;
        try self.strings.append(self.a, text);
        return text;
    }
    fn slot(self: *Reader) Failure!usize {
        if (self.objects.items.len >= 8192) return error.Oversized;
        const n = self.objects.items.len;
        try self.objects.append(self.a, .pending);
        return n;
    }
    fn expectType(self: *Reader, expected: []const u8) Failure!void {
        if (!u.eq(try self.shared(), expected)) return error.Unsupported;
    }
    fn class(self: *Reader, depth: usize) Failure!?[]const u8 {
        if (depth >= 32 or self.pos >= self.bytes.len) return error.Oversized;
        if (self.bytes[self.pos] == 0x85) {
            self.pos += 1;
            return null;
        }
        if (self.bytes[self.pos] != 0x84) {
            const value = self.objects.items[try self.ref(self.objects.items.len)];
            return if (value == .class) value.class else error.Malformed;
        }
        self.pos += 1;
        const index = try self.slot();
        const name = try self.shared();
        const version = try self.integer(true);
        var allowed = false;
        for ([_][]const u8{ "NSObject", "NSValue", "NSNumber", "NSString", "NSMutableString", "NSDictionary", "NSMutableDictionary", "NSAttributedString", "NSMutableAttributedString" }) |known| if (u.eq(name, known)) {
            allowed = true;
            break;
        };
        if (!allowed or version < 0 or version > 1) return error.Unsupported;
        _ = try self.class(depth + 1);
        self.objects.items[index] = .{ .class = name };
        return name;
    }
    fn cstring(self: *Reader) Failure![]const u8 {
        if (self.pos >= self.bytes.len) return error.Malformed;
        if (self.bytes[self.pos] != 0x84) {
            const value = self.objects.items[try self.ref(self.objects.items.len)];
            return if (value == .text) value.text else error.Malformed;
        }
        self.pos += 1;
        const index = try self.slot();
        const text = try self.shared();
        self.objects.items[index] = .{ .text = text };
        return text;
    }
    fn groupedObject(self: *Reader, depth: usize) Failure!Object {
        try self.expectType("@");
        return self.object(depth + 1);
    }
    fn object(self: *Reader, depth: usize) Failure!Object {
        self.visits += 1;
        if (depth >= 32 or self.visits > 8192) return error.Oversized;
        if (self.pos >= self.bytes.len) return error.Malformed;
        if (self.bytes[self.pos] != 0x84) {
            const existing = self.objects.items[try self.ref(self.objects.items.len)];
            return if (existing == .pending or existing == .class) error.Malformed else existing;
        }
        self.pos += 1;
        const index = try self.slot();
        const name = (try self.class(depth + 1)) orelse return error.Malformed;
        const result: Object = result: {
            if (u.eq(name, "NSString") or u.eq(name, "NSMutableString")) {
                try self.expectType("+");
                const bytes = try self.take(try self.readLength());
                if (std.mem.startsWith(u8, bytes, "\xff\xfe")) {
                    if (bytes.len % 2 != 0) return error.Malformed;
                    const units = try self.a.alloc(u16, (bytes.len - 2) / 2);
                    for (units, 0..) |*unit, i| unit.* = std.mem.readInt(u16, bytes[2 + i * 2 ..][0..2], .little);
                    break :result .{ .text = std.unicode.utf16LeToUtf8Alloc(self.a, units) catch return error.Malformed };
                }
                if (!std.unicode.utf8ValidateSlice(bytes)) return error.Malformed;
                break :result .{ .text = bytes };
            }
            if (u.eq(name, "NSNumber")) {
                try self.expectType("*");
                const encoding = try self.cstring();
                if (encoding.len != 1 or std.mem.indexOfScalar(u8, "iIsScCqQ", encoding[0]) == null) return error.Unsupported;
                try self.expectType(encoding);
                break :result .{ .number = try self.integer(std.ascii.isLower(encoding[0])) };
            }
            if (u.eq(name, "NSDictionary") or u.eq(name, "NSMutableDictionary")) {
                try self.expectType("i");
                const count = try self.readLength();
                if (count > 256) return error.Oversized;
                const entries = try self.a.alloc(Entry, count);
                for (entries, 0..) |*entry, i| {
                    const key = try self.groupedObject(depth + 1);
                    if (key != .text) return error.Malformed;
                    for (entries[0..i]) |other| if (u.eq(other.key, key.text)) return error.Malformed;
                    entry.* = .{ .key = key.text, .value = try self.groupedObject(depth + 1) };
                }
                break :result .{ .dict = entries };
            }
            if (u.eq(name, "NSAttributedString") or u.eq(name, "NSMutableAttributedString")) {
                const text = try self.groupedObject(depth + 1);
                if (text != .text or text.text.len > t.max_body) return error.Oversized;
                var ranges: std.ArrayList(Range) = .empty;
                var formats: std.AutoHashMapUnmanaged(i64, []Entry) = .empty;
                while (self.pos < self.bytes.len and self.bytes[self.pos] != 0x86) {
                    if (ranges.items.len >= 8192) return error.Oversized;
                    try self.expectType("iI");
                    const format = try self.integer(true);
                    const length = try self.readLength();
                    if (format < 0 or length == 0) return error.Malformed;
                    const attributes = formats.get(format) orelse blk: {
                        const dict = try self.groupedObject(depth + 1);
                        if (dict != .dict) return error.Malformed;
                        try formats.put(self.a, format, dict.dict);
                        break :blk dict.dict;
                    };
                    try ranges.append(self.a, .{ .length = length, .attributes = attributes });
                }
                break :result .{ .attributed = .{ .text = text.text, .ranges = try ranges.toOwnedSlice(self.a) } };
            }
            return error.Unsupported;
        };
        if (try self.byte() != 0x86) return error.Malformed;
        self.objects.items[index] = result;
        return result;
    }
};
pub fn decode(a: u.Allocator, bytes: []const u8, text: []const u8, attachments: []const t.Attachment) Failure![]t.MessagePart {
    if (bytes.len > t.max_decode) return error.Oversized;
    const header = "\x04\x0bstreamtyped\x81\xe8\x03";
    if (!std.mem.startsWith(u8, bytes, header)) return error.Unsupported;
    var reader = Reader{ .a = a, .bytes = bytes, .pos = header.len };
    const object = try reader.groupedObject(0);
    if (object != .attributed or reader.pos != bytes.len or !u.eq(object.attributed.text, text)) return error.Unsupported;
    // UTF-16 range boundaries must coincide with whole Unicode scalars.
    var boundaries: std.ArrayList(usize) = .empty;
    var utf8 = (std.unicode.Utf8View.init(text) catch return error.Malformed).iterator();
    while (utf8.nextCodepoint()) |cp| {
        const length = std.unicode.utf8CodepointSequenceLength(cp) catch return error.Malformed;
        try boundaries.append(a, utf8.i - length);
        if (cp > 0xffff) try boundaries.append(a, std.math.maxInt(usize));
    }
    try boundaries.append(a, text.len);
    var cursor: usize = 0;
    var parts: std.ArrayList(t.MessagePart) = .empty;
    var seen: std.AutoHashMapUnmanaged(u32, void) = .empty;
    var used: std.StringHashMapUnmanaged(void) = .empty;
    for (object.attributed.ranges) |range| {
        if (range.length >= boundaries.items.len - cursor) return error.Malformed;
        const start = boundaries.items[cursor];
        cursor += range.length;
        const end = boundaries.items[cursor];
        if (start == std.math.maxInt(usize) or end == std.math.maxInt(usize)) return error.Malformed;
        var source_index: ?u32 = null;
        var transfer: ?[]const u8 = null;
        for (range.attributes) |entry| {
            if (u.eq(entry.key, "__kIMMessagePartAttributeName")) {
                if (entry.value != .number or entry.value.number < 0 or entry.value.number > std.math.maxInt(u32)) return error.Malformed;
                source_index = @intCast(entry.value.number);
            } else if (u.eq(entry.key, "__kIMFileTransferGUIDAttributeName")) {
                if (entry.value != .text or entry.value.text.len > 1024) return error.Malformed;
                transfer = entry.value.text;
            }
        }
        const part_index = source_index orelse return error.Unsupported;
        if (transfer == null and parts.items.len > 0) {
            const previous = &parts.items[parts.items.len - 1];
            if (previous.source_index == part_index and previous.kind == .text) {
                previous.text_length = end - previous.text_start.?;
                continue;
            }
        }
        if ((try seen.getOrPut(a, part_index)).found_existing) return error.Unsupported;
        const id = try std.fmt.allocPrint(a, "source:{d}", .{part_index});
        if (transfer) |guid| {
            if (!u.eq(text[start..end], "\xef\xbf\xbc")) return error.Unsupported;
            var digest: [32]u8 = undefined;
            std.crypto.hash.sha2.Sha256.hash(guid, &digest, .{});
            const attachment_id = std.fmt.bytesToHex(digest, .lower);
            var matched: ?[]const u8 = null;
            for (attachments) |attachment| if (u.eq(attachment.id, &attachment_id)) {
                matched = attachment.id;
                break;
            };
            const match = matched orelse return error.Unsupported;
            try used.put(a, match, {});
            try parts.append(a, .{ .id = id, .source_index = part_index, .kind = .attachment, .attachment_id = match });
        } else {
            if (std.mem.indexOf(u8, text[start..end], "\xef\xbf\xbc") != null) return error.Unsupported;
            try parts.append(a, .{ .id = id, .source_index = part_index, .kind = .text, .text_start = start, .text_length = end - start });
        }
    }
    if (cursor != boundaries.items.len - 1) return error.Malformed;
    for (attachments) |attachment| if (!used.contains(attachment.id)) return error.Unsupported;
    return parts.toOwnedSlice(a);
}

test "Foundation ranges locate image GUIDs independently of SQL order and preserve Unicode caption bytes" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var attachments: [2]t.Attachment = undefined;
    for ([_][]const u8{ "22222222-2222-2222-2222-222222222222", "11111111-1111-1111-1111-111111111111" }, 0..) |guid, i| {
        var digest: [32]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(guid, &digest, .{});
        attachments[i] = .{ .id = try a.dupe(u8, &std.fmt.bytesToHex(digest, .lower)), .name = "fixture", .mime_type = "image/png", .bytes = "0" };
    }
    const bytes = @embedFile("fixtures/foundation-parts.bin");
    const text = @embedFile("fixtures/foundation-parts.txt");
    const parts = try decode(a, bytes, text, &attachments);
    try std.testing.expectEqual(@as(usize, 4), parts.len);
    try std.testing.expectEqualStrings("Caption 👩🏽‍💻 ", text[parts[0].text_start.?..][0..parts[0].text_length.?]);
    try std.testing.expectEqualStrings(attachments[1].id, parts[1].attachment_id.?);
    try std.testing.expectEqualStrings(attachments[0].id, parts[3].attachment_id.?);
    try std.testing.expectEqual(@as(?u32, 3), parts[3].source_index);
    try std.testing.expectError(error.Unsupported, decode(a, bytes, text, attachments[0..1]));
    try std.testing.expectError(error.Malformed, decode(a, bytes[0 .. bytes.len - 1], text, &attachments));
}
