//! Headless driver for the same worker used by the GUI. No send is generated by
//! default. --control consumes explicit JSON commands on stdin for fixture tests.
const std = @import("std");
const Config = @import("client.zig").Config;
const Worker = @import("client.zig").Worker;
const u = @import("common.zig");
const Media = @import("client.zig").Media;
const types = @import("protocol.zig").types;
pub fn main(init: std.process.Init) !void {
    const config = try Config.parse(init);
    const cache_lock = try config.lockCache();
    defer _ = u.c.close(cache_lock);
    var worker = Worker{ .io = init.io, .config = config };
    try worker.start();
    defer worker.shutdown();
    if (config.control) {
        try control(init, &worker);
        return;
    }
    var selected = false;
    const deadline = u.now() + 90000;
    while (u.now() < deadline) {
        if (worker.take()) |v| {
            defer v.destroy();
            if (v.diagnostics.auth_blocked) {
                const d = v.diagnostics.transport;
                std.debug.print("{s}\n{s} (curl {d}, verification {d})\n", .{
                    v.status,
                    d.detail,
                    d.curl_code,
                    d.verify_result,
                });
                return error.ConnectionNeedsAttention;
            }
            if (v.online and !selected and v.snapshot.chats.len > 0) {
                try worker.push(.{ .kind = .select, .key = v.snapshot.chats[0].value.id });
                selected = true;
            }
            if (v.online and (v.snapshot.messages.len > 0 or v.snapshot.chats.len == 0)) {
                std.debug.print("Connected: conversations={d}, cached_messages={d}, send_direct={}, reply_existing={}\n", .{
                    v.snapshot.chats.len,
                    v.snapshot.messages.len,
                    v.send_direct,
                    v.reply_existing,
                });
                return;
            }
        }
        try std.Io.sleep(init.io, .fromMilliseconds(50), .awake);
    }
    return error.ClientProbeTimedOut;
}
fn control(init: std.process.Init, worker: *Worker) !void {
    const a = init.arena.allocator();
    var media = Media{ .io = init.io, .config = worker.config };
    try media.start();
    defer media.shutdown();
    var input: std.ArrayList(u8) = .empty;
    _ = u.c.fcntl(0, u.c.F_SETFL, @as(c_int, u.c.O_NONBLOCK));
    while (true) {
        var buf: [4096]u8 = undefined;
        const n = u.c.read(0, &buf, buf.len);
        if (n == 0) return;
        if (n > 0) try input.appendSlice(a, buf[0..@intCast(n)]);
        while (std.mem.indexOfScalar(u8, input.items, '\n')) |end| {
            const line = input.items[0..end];
            if (u.eq(line, "quit")) return;
            const kind = try std.json.parseFromSliceLeaky(
                struct { kind: []const u8 },
                a,
                line,
                .{ .ignore_unknown_fields = true },
            );
            if (u.eq(kind.kind, "media_context")) {
                const ctx = try std.json.parseFromSliceLeaky(struct {
                    epoch: []const u8,
                    chat: []const u8 = "",
                    credentials: u64 = 0,
                    online: bool = true,
                    avatars: bool = true,
                }, a, line, .{ .ignore_unknown_fields = true });
                _ = try media.context(ctx.epoch, ctx.chat, ctx.credentials, ctx.online, ctx.avatars);
            } else if (u.eq(kind.kind, "media")) {
                const request = try std.json.parseFromSliceLeaky(
                    struct { asset: types.AssetRef },
                    a,
                    line,
                    .{ .ignore_unknown_fields = true },
                );
                try media.request(request.asset);
            } else {
                const cmd = try std.json.parseFromSlice(Worker.Command, a, line, .{});
                try worker.push(cmd.value);
            }
            std.mem.copyForwards(u8, input.items, input.items[end + 1 ..]);
            input.items.len -= end + 1;
        }
        if (media.take()) |result| {
            defer media.release(result);
            const raw = try u.json(a, .{ .media = .{
                .state = result.state,
                .key = result.key,
                .generation = result.generation,
                .width = result.pixels.width,
                .height = result.pixels.height,
                .bytes = result.pixels.bytes,
                .reason = std.mem.sliceTo(&result.reason, 0),
            } });
            _ = u.c.write(1, raw.ptr, raw.len);
            _ = u.c.write(1, "\n", 1);
        }
        if (worker.take()) |v| {
            defer v.destroy();
            const selected_title = for (v.snapshot.chats) |chat| {
                if (u.eq(chat.value.id, v.snapshot.selected)) break v.snapshot.directory.conversation(a, chat.value);
            } else "";
            const raw = try u.json(a, .{
                .online = v.online,
                .status = v.status,
                .chats = v.snapshot.chats.len,
                .messages = v.snapshot.messages.len,
                .pending = v.snapshot.pending.len,
                .selected = v.snapshot.selected,
                .selected_title = selected_title,
                .directory_revision = v.snapshot.directory.fingerprint(),
                .ack = v.ack,
                .diagnostics = v.diagnostics,
            });
            _ = u.c.write(1, raw.ptr, raw.len);
            _ = u.c.write(1, "\n", 1);
        }
        try std.Io.sleep(init.io, .fromMilliseconds(20), .awake);
    }
}
