//! Headless driver for the same worker used by the GUI. No send is generated by
//! default. --control consumes explicit JSON commands on stdin for fixture tests.
const std = @import("std");
const Config = @import("client/Config.zig");
const Worker = @import("client/Worker.zig");
const u = @import("common.zig");
pub fn main(init: std.process.Init) !void {
    const config = try Config.parse(init);
    var worker = Worker{ .io = init.io, .config = config };
    try worker.start();
    defer worker.shutdown();
    if (config.control) {
        try control(init, &worker);
        return;
    }
    var selected = false;
    const deadline = u.now() + 90000;
    while (u.now() < deadline) {
        if (worker.take()) |v| {
            defer v.destroy();
            if (v.diagnostics.auth_blocked) {
                const d = v.diagnostics.transport;
                std.debug.print("{s}\n{s} (curl {d}, verification {d})\n", .{ v.status, d.detail, d.curl_code, d.verify_result });
                return error.ConnectionNeedsAttention;
            }
            if (v.online and !selected and v.snapshot.chats.len > 0) {
                try worker.push(.{ .kind = .select, .key = v.snapshot.chats[0].value.id });
                selected = true;
            }
            if (v.online and (v.snapshot.messages.len > 0 or v.snapshot.chats.len == 0)) {
                std.debug.print("Connected: conversations={d}, cached_messages={d}, send_direct={}, reply_existing={}\n", .{ v.snapshot.chats.len, v.snapshot.messages.len, v.send_direct, v.reply_existing });
                return;
            }
        }
        try std.Io.sleep(init.io, .fromMilliseconds(50), .awake);
    }
    return error.ClientProbeTimedOut;
}
fn control(init: std.process.Init, worker: *Worker) !void {
    const a = init.arena.allocator();
    var input: std.ArrayList(u8) = .empty;
    _ = u.c.fcntl(0, u.c.F_SETFL, @as(c_int, u.c.O_NONBLOCK));
    while (true) {
        var buf: [4096]u8 = undefined;
        const n = u.c.read(0, &buf, buf.len);
        if (n == 0) return;
        if (n > 0) try input.appendSlice(a, buf[0..@intCast(n)]);
        while (std.mem.indexOfScalar(u8, input.items, '\n')) |end| {
            const line = input.items[0..end];
            if (u.eq(line, "quit")) return;
            const cmd = try std.json.parseFromSlice(Worker.Command, a, line, .{});
            try worker.push(cmd.value);
            std.mem.copyForwards(u8, input.items, input.items[end + 1 ..]);
            input.items.len -= end + 1;
        }
        if (worker.take()) |v| {
            defer v.destroy();
            const raw = try u.json(a, .{ .online = v.online, .status = v.status, .chats = v.snapshot.chats.len, .messages = v.snapshot.messages.len, .pending = v.snapshot.pending.len, .selected = v.snapshot.selected, .ack = v.ack, .dark_mode = v.dark_mode, .diagnostics = v.diagnostics });
            _ = u.c.write(1, raw.ptr, raw.len);
            _ = u.c.write(1, "\n", 1);
        }
        try std.Io.sleep(init.io, .fromMilliseconds(20), .awake);
    }
}
